# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 
name: svenenman/zephyrus:micro_test_env
username: $USERNAME
password: $PASSWORD
email: $EMAIL

pipelines:
  default:
    - step:
        script: 
          - mkdir build
          - cd build
          - cmake ../Source
          - make microtests